let country_code = {
  "zh-CHS": "Chinese",
  "ar-SA": "Arabic ",
  "bg-BG": "Bulgaria",
  "ca-ES": "Catalan",
  "zh-TW": "Chinese",
  "cs-CZ": "Czech",
  "da-DK": "Danish",
  "de-DE": "German",
  "el-GR": "Greek",
  "en-US": "English",
  "es-ES": "Spanish",
  "fi-FI": "Finnish",
  "fr-FR": "French",
  "he-IL": "Hebrew",
  "hu-HU": "Hungaria",
  "is-IS": "Icelandi",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "ko-KR": "Korean ",
  "nl-NL": "Dutch ",
  "nb-NO": "Norwegia",
  "pl-PL": "Polish ",
  "pt-BR": "Portuguese",
  "rm-CH": "Romansh",
  "ro-RO": "Romanian",
  "ru-RU": "Russian",
  "hr-HR": "Croatian",
  "sk-SK": "Slovak ",
  "sq-AL": "Albanian",
  "sv-SE": "Swedish",
  "th-TH": "Thai ",
  "tr-TR": "Turkish",
  "ur-PK": "Urdu ",
  "id-ID": "Indonesian",
  "uk-UA": "Ukrainian",
  "be-BY": "Belarusian",
  "sl-SI": "Slovenian",
  "et-EE": "Estonian",
  "lv-LV": "Latvian",
  "lt-LT": "Lithuani",
  "tg-TJ": "Tajik ",
  "fa-IR": "Persian",
  "vi-VN": "Vietnamese",
  "hy-AM": "Armenian",
  "az-AZ": "Azeri (Latin)",
  "eu-ES": "Basque ",
  "hsb-DE": "Upper Sorbian",
  "mk-MK": "Macedonian",
  "tn-ZA": "Setswana",
  "xh-ZA": "isiXhosa",
  "zu-ZA": "isiZulu",
  "af-ZA": "Afrikaans",
  "ka-GE": "Georgian",
  "fo-FO": "Faroese",
  "hi-IN": "Hindi ",
  "mt-MT": "Maltese",
  "se-NO": "Sami ",
  "ms-MY": "Malay ",
  "kk-KZ": "Kazakh ",
  "ky-KG": "Kyrgyz ",
  "sw-KE": "Swahili",
  "tk-TM": "Turkmen",
  "uz-UZ": "Uzbek (Latin)",
  "tt-RU": "Tatar ",
  "bn-IN": "Bangla ",
  "pa-IN": "Punjabi",
  "gu-IN": "Gujarati",
  "or-IN": "Oriya ",
  "ta-IN": "Tamil ",
  "te-IN": "Telugu ",
  "kn-IN": "Kannada",
  "ml-IN": "Malayalam",
  "as-IN": "Assamese",
  "mr-IN": "Marathi",
  "sa-IN": "Sanskrit",
  "mn-MN": "Mongolian",
  "bo-CN": "Tibetan",
  "cy-GB": "Welsh ",
  "km-KH": "Khmer ",
  "lo-LA": "Lao - Lao",
  "gl-ES": "Galician",
  "kok-IN": "Konkani",
  "syr-SY": "Syriac ",
  "si-LK": "Sinhala",
  "chr-US": "Cherokee",
  "iu-CA": "Inuktitut",
  "am-ET": "Amharic",
  "ne-NP": "Nepali ",
  "fy-NL": "Frisian",
  "ps-AF": "Pashto ",
  "fil-PH": "Filipino",
  "dv-MV": "Divehi ",
  "ha-NG": "Hausa ",
  "yo-NG": "Yoruba ",
  "quz-BO": "Quechua",
  "nso-ZA": "Sesothosa",
  "ba-RU": "Bashkir",
  "lb-LU": "Luxembourgish",
  "kl-GL": "Greenlandic",
  "ig-NG": "Igbo ",
  "ti-ET": "Tigrinya",
  "haw-US": "Hawiian",
  "ii-CN": "Yi ",
  "arn-CL": "Mapudung",
  "moh-CA": "Mohawk ",
  "br-FR": "Breton ",
  "ug-CN": "Uyghur ",
  "mi-NZ": "Maori ",
  "oc-FR": "Occitan",
  "co-FR": "Corsican",
  "gsw-FR": "Alsatian",
  "sah-RU": "Sakha ",
  "quc-GT": "K'iche ",
  "rw-RW": "Kinyarwa",
  "wo-SN": "Wolof -",
  "prs-AF": "Dari ",
  "gd-GB": "Scottish",
  "ku-Arab-IQ": "Central",
  "ar-IQ": "Arabic ",
  "ca-ES": "Valencia",
  "zh-CN": "Chinese",
  "de-CH": "German ",
  "en-GB": "English",
  "es-MX": "Spanish",
  "fr-BE": "French ",
  "it-CH": "Italian",
  "nl-BE": "Dutch ",
  "nn-NO": "Norwegia",
  "pt-PT": "Portugue",
  "sr-CS": "Serbian",
  "sv-FI": "Swedish",
  "ur-IN": "Urdu ",
  "az-AZ": "Azeri ",
  "dsb-DE": "Lower",
  "tn-BW": "Setswana",
  "se-SE": "Sami ",
  "ga-IE": "Irish ",
  "ms-BN": "Malay ",
  "uz-UZ": "Uzbek ",
  "bn-BD": "Bangla ",
  "pa-PK": "Punjabi",
  "ta-LK": "Tamil ",
  "mn-CN": "Mongolian",
  "sd-PK": "Sindhi ",
  "iu-CA": "Inuktitut",
  "tzm-DZ": "Tamazight",
  "ff-SN": "Pular ",
  "quz-EC": "Quechua",
  "ti-ER": "Tigrinya",
  "ar-EG": "Arabic ",
  "zh-HK": "Chinese",
  "de-AT": "German ",
  "en-AU": "English",
  "es-ES": "Spanish",
  "fr-CA": "French ",
  "sr-CS": "Serbian",
  "se-FI": "Sami ",
  "quz-PE": "Quechua,",
  "ar-LY": "Arabic ",
  "zh-SG": "Chinese",
  "de-LU": "German ",
  "en-CA": "English",
  "es-GT": "Spanish",
  "fr-CH": "French ",
  "hr-BA": "Croatian",
  "smj-NO": "Sami",
  "tzm-MA": "Central",
  "ar-DZ": "Arabic ",
  "zh-MO": "Chinese",
  "de-LI": "German ",
  "en-NZ": "English",
  "es-CR": "Spanish",
  "fr-LU": "French ",
  "bs-BA": "Bosnian",
  "smj-SE": "Sami",
  "ar-MA": "Arabic ",
  "en-IE": "English",
  "es-PA": "Spanish",
  "fr-MC": "French ",
  "sr-BA": "Serbian",
  "sma-NO": "Sami",
  "ar-TN": "Arabic ",
  "en-ZA": "English",
  "es-DO": "Spanish",
  "sr-BA": "Serbian",
  "sma-SE": "Sami",
  "ar-OM": "Arabic ",
  "en-JM": "English",
  "es-VE": "Spanish",
  "bs-BA": "Bosnian",
  "sms-FI": "Sami (Skolt)",
  "ar-YE": "Arabic ",
  "en-029": "English",
  "es-CO": "Spanish",
  "sr-RS": "Serbian",
  "smn-FI": "Sami ",
  "ar-SY": "Arabic ",
  "en-BZ": "English",
  "es-PE": "Spanish",
  "sr-RS": "Serbian",
  "ar-JO": "Arabic ",
  "en-TT": "English",
  "es-AR": "Spanish",
  "sr-ME": "Serbian",
  "ar-LB": "Arabic ",
  "en-ZW": "English",
  "es-EC": "Spanish",
  "sr-ME": "Serbian",
  "ar-KW": "Arabic ",
  "en-PH": "English",
  "es-CL": "Spanish",
  "ar-AE": "Arabic ",
  "es-UY": "Spanish",
  "ar-BH": "Arabic ",
  "es-PY": "Spanish",
  "ar-QA": "Arabic ",
  "en-IN": "English",
  "es-BO": "Spanish",
  "en-MY": "English",
  "es-SV": "Spanish",
  "en-SG": "English",
  "es-HN": "Spanish",
  "es-NI": "Spanish",
  "es-PR": "Spanish",
  "es-US": "Spanish",
  "zh-CHT": "Chinese",
};
